title: GeneScope
description: "Social Media for Del Norte High School"
owner_name: Avika Prasad
github_username: avikaprasad22
github_repo: "genescope"
baseurl: "/genescope"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
layouts_dir: _layouts
header_pages:
  - navigation/about.md
  - navigation/search.md
  - navigation/blog.md

defaults:
  - scope:
      path: "" # Applies to all files
    values:
      layout: tailwind